# Copyright 2019 OpenStax Poland
# Licensed under the MIT license. See LICENSE file in the project root for
# full license text.

# Enforce best practices and protect against common mistakes in JSX and React.
#
# This is an alternative to openstax-poland/base which includes additional rules
# from eslint-plugin-react.

extends:
  - ../base.yml
  - plugin:react/recommended

settings:
  react:
    version: 16.2.0

rules:
  # Forbid use of .bind() and arrow functions as JSX callbacks, as they are not
  # comparable and can cause unnecessary re-renders.
  react/jsx-no-bind: error

  # Forbid uses of fragments with a single child element.
  react/jsx-no-useless-fragment: error

  # Warn against dangerous usage of this.state in calls to this.setState.
  react/no-access-state-in-setstate: warn

  # Warn against uses of this.setState within componentDidMount and
  # componentDidUpdate, as this will trigger an additional render.
  react/no-did-mount-set-state: warn
  react/no-did-update-set-state: warn

  # Properties in state must be used.
  react/no-unused-state: error

  # Forbid usage of unsafe lifecycle methods.
  react/no-unsafe: error

  # Don't use shouldComponentUpdate within a React.PureComponent, as then
  # extending PureComponent is meaningless.
  react/no-redundant-should-component-update: error

  # Use of this in functional components is most likely a mistake.
  react/no-this-in-sfc: error

  # Protect against common typos.
  react/no-typos: error

  # Calling this.setState within componentWillUpdate can lead to indeterminate
  # state.
  react/no-will-update-set-state: error

  # React components must be defined as ES6 classes.
  react/prefer-es6-class: error

  # Stateless components must be written as functions.
  react/prefer-stateless-function: error

  # Disallow passing children to void DOM elements.
  react/void-dom-elements-no-children: error
